### ISSUE TITLE
Pull the code client code into a Go SDK

### ISSUE THREAD

**Issue by arschles** [deis/workflow-cli#18]
Moved from https://github.com/deis/workflow/issues/221

The client should be structured as:

- A package or set of packages, that other Go projects can `import`
- A `main` package that wraps the aforementioned packages into a CLI

**Comment by Joshua-Anderson** [comment]
Right now the layout is:

`.`: main package & cli entrypoint
`parser`: command line argument parser
`cmd`: workflow-cli actions
`pkg`: tiny standalone packages
`version`: package used to set `cli`

All of the api interface stuff that you would like to pull out is in `controller`, more specifically `controller/models`.

What are your plans to pull it into a SDK?

Are you planning to create a new repository or just rename/document/reorganize `controller` so it can be more easily used as a sdk?

**Comment by bacongobbler** [comment]
The controller package is the one we'd like to pull out. Essentially we'd like to create multiple repositories for different language bindings so third parties can use the SDKs to create their own clients.

**Comment by bacongobbler** [comment]
controller-go, controller-go, controller-go etc.

**Comment by Joshua-Anderson** [comment]
If there is still interest in this, I'm happy to help!

**Comment by arschles** [comment]
I'm certainly still interested in seeing this done!

**Comment by arschles** [comment]
@Joshua-Anderson I've just created https://github.com/deis/controller-sdk-go for use to house the SDK code

**Comment by Joshua-Anderson** [comment]
This has been done!
