### ISSUE TITLE
Build and publish workflow-cli within 1 container

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-cli#180]
Right now we rely on 2 different containers to build and publish the workflow-cli. This means we volume mount the `_dist` directory which pollutes the workspace. This is causing us pain where we are uploading old versions of the cli.

Instead, we should build the CLI within 1 image and then publish the `_dist` directory from that same container. The workflow should look like this -

`build workflow-cli dev image -> run tests with dev image -> build cli -> publish cli`

**Comment by Joshua-Anderson** [comment]
We may still want to host mount the vendor directory for caching.

**Comment by jchauncey** [comment]
yeah we could explicitly mount the vendor dir
