### ISSUE TITLE
Implement functional tests from content removed from e2e

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/workflow-cli#182]
`deis help` and `deis version` tests have been removed from e2e and need to be implemented in the CLI.

**Comment by Joshua-Anderson** [comment]
`deis version` now has tests.

**Comment by vdice** [comment]
It looks like https://github.com/deis/workflow-cli/issues/248 was created to track the `deis help` test additions mentioned in this issue.  As this ticket isn't marked for `v2.6`, and the latter half of this ticket appears to be finished, I'm going to close this.
