### ISSUE TITLE
Proposal: deis:info should show service IP

### ISSUE THREAD

**Issue by krancour** [deis/workflow-cli#184]
`deis:info` currently shows output like this:

```
$ deis info -a example-go
=== example-go Application
updated:  2016-08-17T17:20:33Z
uuid:     60135b08-45a3-456f-8de1-d347b4a76726
created:  2016-08-17T17:20:14Z
url:      example-go.192.168.99.101.xip.io
owner:    kent
id:       example-go

=== example-go Processes
--- cmd:
example-go-cmd-918069087-4p1lu up (v2)

=== example-go Domains
example-go
```

The `url` field is very useful for anyone wishing to connect to a _routable_ service from outside the cluster, but I believe there are frequently circumstances where someone might want to know the IP of a service _within_ the cluster-- for instance, to connect to services together without having the router in between them.

I propose that `deis:info` should be enhanced to display the internal service IP.

(Yes, you can get this info from `kubectl`, but we shouldn't assume all `deis` users [i.e. app operators] necessarily have access to `kubectl` [as a _cluster_ operator would].)

**Comment by Joshua-Anderson** [comment]
@krancour: The deis cli gets the url from the list of domains returned by the controller. The controller would need to return the service IP along with every other domain.

**Comment by krancour** [comment]
Yep. I realize that. A complementary change to the controller would be required. I neglected to mention that.

**Comment by Joshua-Anderson** [comment]
I'd recommend opening an issue in the controller in addition to this one so it can be better tracked.

**Comment by bacongobbler** [comment]
Closing as per https://github.com/deis/controller/issues/987#issuecomment-246816570
