### ISSUE TITLE
rename binary as workflow

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow-cli#20]
Right now the Makefile dumps out a binary called `deis`. Since the project is being renamed to `workflow`, we should also update this and any other relevant documentation/build scripts etc.

refs deis/deis#4952

**Comment by mboersma** [comment]
I am against this: `deis` is familiar and unique. It also reinforces the product name, if you want to look at it from a marketing point of view, whereas `workflow` is generic. Our BDFL has also said it should stay as `deis`.

**Comment by bacongobbler** [comment]
To anyone reading this: please vote by making a reaction to the OP so we can get a tally. If you feel strongly about your opinion, please feel free to comment as well. :)

**Comment by sgoings** [comment]
Looks like this issue isn't going to get any traction. I vote to close this and the referenced issues:

- https://github.com/deis/deis.io/issues/150

But leave the following issues open, as they're issues that seem to fall in line with the "deis as company, workflow as product" methodology:

- https://github.com/deis/charts/issues/126 (implemented via https://github.com/deis/charts/pull/157 and https://github.com/sgoings/chart-mate/pull/5)

Still up for discussion would be:

- https://github.com/deis/charts/issues/155
