### ISSUE TITLE
[Meta] Improve error messages

### ISSUE THREAD

**Issue by arschles** [deis/workflow-cli#23]
See https://github.com/deis/workflow/pull/349/files#r52217168 for an example.

Replaces deis/workflow#356

**Comment by bacongobbler** [comment]
error messages have been improved thanks to @helgi's work on the controller.

**Comment by helgi** [comment]
I was somewhat hoping we'd either not pass through messages to the CLI or the CLI would at least not just dump out bunch of information, such as the status code unless in verbose mode
