### ISSUE TITLE
Provide server version info in 'deis version'

### ISSUE THREAD

**Issue by arschles** [deis/workflow-cli#25]
From @jchauncey's comment in https://github.com/deis/deis/issues/4674:

> It would be nice if the deis cli had a version command that returned the version of the server running and the version of the cli (like the docker version command)

We could add a flag to `deis version` (#328) to provide more verbose information similar to `docker version`, like so:

```
><> deis version -a
Client version: 2.0.0-dev
Client API version: 2.0
Go version (client): go1.5.2
Git commit (client): foobar
OS/Arch (client): linux/amd64
Server version: 2.0.0-dev
Server API version: 2.0
Go version (server): go1.5.2
Git commit (server): foobar
OS/Arch (server): linux/amd64
```

Alternatively, We could turn it into a JSON object for formatting:

```
><> deis version -a
{
  "Client" {
    "Version": "2.0.0-dev",
    "APIVersion": "2.0",
    "GoVersion": "go1.5.2".
    "Commit": "foobar",
    "Arch": "amd64",
    "OS": "linux"
  },
  "Server": {
    "Version": "2.0.0-dev",
    "APIVersion": "2.0",
    "GoVersion": "go1.5.2".
    "Commit": "foobar",
    "Arch": "amd64",
    "OS": "linux"
  }
```

Which could be handy in the future for features like `deis version -f '{{.Client.Version}}'`, which formats the version output through the given Go template (similar to `docker inspect -f`):

```
><> deis version -a -f '{{ .Client.Version }}'
2.0.0-dev
```

Note that deis/workflow#329 tracks server side work, and this issue tracks client side work.

**Comment by Joshua-Anderson** [comment]
@bacongobbler Are you working on this right now? Mind if I steal it? 😈

**Comment by bacongobbler** [comment]
Go right ahead. :)
