### ISSUE TITLE
Restrict the number of times a person can fail a login attempt

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-cli#27]
See deis/controller#544

**Comment by Joshua-Anderson** [comment]
I'm not sure this has a CLI portion at all. The api will just return an error status code and the CLI should properly handle it.

@jchauncey Can this be closed in favor of the controller issue?

**Comment by Joshua-Anderson** [comment]
I don't think this issue will require any CLI changes, so I'm going to close this in favor of the controller issue.
