### ISSUE TITLE
use go-rootcerts to support custom PKI on darwin

### ISSUE THREAD

**Issue by tmc** [deis/workflow-cli#271]
see https://github.com/hashicorp/go-rootcerts

**Comment by bacongobbler** [comment]
Until go 1.8 is out this sounds like a good workaround. If you feel like making a PR, this would be a good opportunity.

**Comment by bacongobbler** [comment]
this will be fixed in Go 1.7.4: https://groups.google.com/forum/#!topic/golang-announce/2lP5z9i9ySY

**Comment by mboersma** [comment]
Fixed in #281.
