### ISSUE TITLE
The CLI should accept any path provided by DEIS_PROFILE

### ISSUE THREAD

**Issue by jchauncey** [deis/workflow-cli#28]
Right now the json files can only exists in the `.deis` directory.

**Comment by bacongobbler** [comment]
Personally I'd rather deprecate DEIS_PROFILE in favor of a global `--config-file` flag to specify where to read config from, defaulting to `~/.deis/client.json`

**Comment by jchauncey** [comment]
Yeah I actually like that better. Might try and add that soon.

**Comment by Joshua-Anderson** [comment]
I'm torn on this. I think that being able to pass a path is adds nice flexibility, but `$DEIS_PROFILE` fits a multi-cluster workflow really well.

Being able to `export DEIS_PROFILE=staging` or `export DEIS_PROFILE=production` is super quick and intuitive way to switch between multiple clusters.

**Comment by bacongobbler** [comment]
There's nothing stopping you from replicating the same behavior with `--config-file`. It just adds more flexibility for users. For example, here's a script to replicate the same behavior as $DEIS_PROFILE with `--config-file`:

```
#!/bin/bash

DEIS_PROFILE=${DEIS_PROFILE:-client}
deis --config-file "$HOME/.deis/$DEIS_PROFILE.json" $@
```

Users may also want to specify a global client config path to share one config across all users of a system (e.g. `/etc/deis/client.json`), which the client currently does not allow.

**Comment by jchauncey** [comment]
So I think keeping DEIS_PROFILE while accepting `--config` or `--client-config` is perfectly acceptable. I would just make the CLI option override the env var.

**Comment by sstarcher** [comment]
I think adding --client-config is a good idea, but any CLI flag like that should be backed by an environment variable or an additional command should be supported to set the client config long term.

Similar with K8S you can specify ```--kubeconfig``` or ```kubectl config``` or ```KUBE_something_something``` environment variable

**Comment by Joshua-Anderson** [comment]
My proposal is that:
1. `$DEIS_PROFILE` should support file-paths in addition to just a name.
2. A global flag called `--config` acts identically to `$DEIS_PROFILE`

**Comment by Joshua-Anderson** [comment]
A command line flag is going to be needed to run tests in parallel. Otherwise all tests have to share the same `$DEIS_PROFILE`, so I'm going to start work on this issue.
