### ISSUE TITLE
Write an intergration test suite

### ISSUE THREAD

**Issue by arschles** [deis/workflow-cli#31]
This or a related repository should have integration tests, which exercise the `deis` CLI against a *real* Deis cluster. The tests should run the CLI through the entire suite of normal operations. This issue is highly related to https://github.com/deis/workflow-e2e/issues/132, which is in-progress and prescribes such tests.

**Comment by Joshua-Anderson** [comment]
Jenkins now runs e2e on this repository and e2e is sticking with the CLI for the foreseeable future.

@arschles Can this be closed?

**Comment by arschles** [comment]
yep, closing
