### ISSUE TITLE
Url : permission denied

### ISSUE THREAD

**Issue by mamta-g** [deis/workflow-cli#314]
On accessing with curl command as mentioned in the documentation, I get the below error:
**_Anonymous caller does not have storage.objects.get access to workflow-cli-release/deis-stable-linux-amd64._**
Can someone please grant the permission or make it public ?

![deis access denied](https://user-images.githubusercontent.com/26457208/71611537-b85be700-2bbf-11ea-9992-7e412f4e1976.png)

**Comment by Cryptophobia** [comment]
Deis Workflow is end-of-lifed (EOL) and no longer maintained project. The google storage links have been shut down.

If you are interested in this project, check out the open source fork at https://github.com/teamhephy

You can also join our slack channel if you are interested in using the project: https://slack.teamhephy.com

You can pull the hephy cli from this Google Storage bucket:
https://storage.googleapis.com/hephy-workflow-cli-release
