### ISSUE TITLE
Proposal: support for multiple Deis clusters

### ISSUE THREAD

**Issue by arschles** [deis/workflow-cli#38]
As far as I can tell, the CLI stores all auth and registration information in `$HOME/.deis/client.json`, which means that the user has to use the same Deis cluster for all projects on their machine. Some users might like to use different Deis clusters on a per-project basis.

One possibility to accomplish this is to have the CLI look for a config file in the current directory, and fall back to the global one.

I'm not sure if we accomplish multiple Deis clusters in a different way, but if we have, I haven't found it.

**Comment by helgi** [comment]
You can set `$DEIS_PROFILE` on your env to look for a different config, that's how we currently allow people to use multiple configs

**Comment by Joshua-Anderson** [comment]
Also see #28 for potential expansions of multiple cluster support.

**Comment by Joshua-Anderson** [comment]
Since both `$DEIS_PROFILE` and the `--config` flag exist and take both a path or a name, I'm going to close this as implemented.
