### ISSUE TITLE
Allow commenting out .env vars

### ISSUE THREAD

**Issue by jeroenvisser101** [deis/workflow-cli#44]
When doing a `config:push`, the regex doesn't match and fails pushing variables, while it would be nice to temporarily turn certain `.env` vars off.

**Comment by Joshua-Anderson** [comment]
I created PR #47 for this!

**Comment by jeroenvisser101** [comment]
@Joshua-Anderson wow, that's great, thanks! Any chance you could edit it so it would also accept empty lines?

**Comment by Joshua-Anderson** [comment]
This PR also fixes the problem with empty lines!

**Comment by jeroenvisser101** [comment]
@Joshua-Anderson That's awesome, thank you so much!
