### ISSUE TITLE
Weird UX on deis create --no-remote

### ISSUE THREAD

**Issue by krancour** [deis/workflow-cli#56]
This issue _might_ be with the controller and not the CLI (I have not dug far enough to know yet), but CLI is my best guess.

```
[kent@mbp ~]$ deis create --no-remote
Creating Application... done, created queens-gemstone
remote available at ssh://git@deis-builder.krancour.deis.ninja:2222/queens-gemstone.git
```

"remote available at ...?"  I asked for _no_ remote.  Indeed, no `deis` remote gets created locally _and_ I'll admit it's useful info insofar as I can infer the app name from it, but even so... it looks pretty weird.

It would probably be better to just respond saying the app named <whatever> had been created.

**Comment by bacongobbler** [comment]
no remote is created, but we still display the remote so you can reference it elsewhere if you wish. This was part of the original design. :)

**Comment by krancour** [comment]
Ah.  So the idea here is that `--no-remote` means don't create a remote _now_.  I'm informed of what it is because I may want to create a remote myself _later_.

Got it.

Nevertheless, I think this is a somewhat jarring user experience.  The more I have talked to users, the more and more interest I here in `deis pull` as their deployment mechanism of choice.  (In many cases, people already have CI pipelines that they like and those pipelines output Docker images.)  This is a large class of user who won't care about the remote _ever_.  From their perspective, the output of this command is still pretty odd.

Maybe we can split the difference and add text that indicates, "If you want to add a git remote for this app later, it's address is: <address>"?

**Comment by bacongobbler** [comment]
> Maybe we can split the difference and add text that indicates, "If you want to add a git remote for this app later, its address is: <address>"?

Yeah or just say "If you want to add a git remote for this app later, use `deis git:remote`". That's even less confusing, and probably less taxing on the eyes since it doesn't have a git remote URL dumped to the screen. :)

**Comment by krancour** [comment]
> Yeah or just say "If you want to add a git remote for this app later, use `deis git:remote`".

We can improve even further by saying:

```
If you want to add a git remote for this app later, use `deis git:remote -a zanier-undertow`
```

If you don't specify the app name, as with many other commands, the app name is inferred from the name of the current working directory and most of the time, that's going to yield a remote with a URL like:

```
ssh://git@deis-builder.krancour.deis.ninja:2222/example-go.git
```

And that's usually going to be wrong.
