### ISSUE TITLE
Change user-agent string for release

### ISSUE THREAD

**Issue by mboersma** [deis/workflow-cli#70]
Currently controller logs show it still reports `v2.0.0-dev`:
```
INFO Not scaling RC webbed-traverse-v2-cmd in Namespace webbed-traverse to 0 replicas. Already at desired replicas
10.200.1.8 "POST /v2/apps/webbed-traverse/config/ HTTP/1.1" 201 242 "Deis Client v2.0.0-dev"
10.200.1.8 "GET /v2/apps/webbed-traverse/config/ HTTP/1.1" 200 230 "Deis Client v2.0.0-dev"
10.200.1.8 "GET /v2/apps/webbed-traverse/ HTTP/1.1" 200 173 "Deis Client v2.0.0-dev"
```

**Comment by helgi** [comment]
https://github.com/deis/controller/blob/master/rootfs/deis/__init__.py

**Comment by bacongobbler** [comment]
@helgi yes this needs to be done in the controller as well, but I think @mboersma is referring to https://github.com/deis/workflow-cli/blob/7283e7c775938e0f61e9670515ef62d1fdab0076/version/version.go#L4

**Comment by arschles** [comment]
@bacongobbler @mboersma do you think it's worth pulling the version into a linker flag?

**Comment by Joshua-Anderson** [comment]
https://github.com/deis/workflow-cli/blob/master/version/version.go#L11 is already a linker flag. We just need to use this variable for the user-agent string.
