### ISSUE TITLE
upload builds to S3

### ISSUE THREAD

**Issue by bacongobbler** [deis/workflow-cli#73]
bintray's terms of use does not allow development builds to be uploaded. Because of this, we hit https://github.com/deis/workflow/issues/282. Moving us back to S3 and updating `install-v2.sh` would help us in this regard.

Not labelling as a showstopper for v2 but certainly something we need to do ASAP.

**Comment by arschles** [comment]
possibly related to https://github.com/deis/minio/issues/108, as the builds could be uploaded to the same GCS bucket..

**Comment by bacongobbler** [comment]
Places so far that I've seen that need updating once we make this change include:

 - deis/deis.io (install scripts)
 - deis/workflow-e2e (fetches client binary by sha)

**Comment by arschles** [comment]
A Google Cloud Storage bucket has been created in the `deis-downloads` project at https://console.cloud.google.com/storage/browser/workflow-cli/?project=deis-downloads

**Comment by arschles** [comment]
See https://github.com/deis/deisrel/pull/88 for an example implementation
