### ISSUE TITLE
Fix the README install language

### ISSUE THREAD

**Issue by arschles** [deis/workflow-cli#9]
Currently it says:

```
Currently the only way to use the go version of the deis client is to build it yourself. To build the deis client, you need to have go, glide, and make installed. Then run make build.
```

This isn't true. After #7 is done, this repo will be publishing it to bintray (although deis/workflow was already publishing it), so the README should say that

**Comment by bacongobbler** [comment]
@arschles I'd be happy to take this off your hand if you need help

**Comment by arschles** [comment]
@bacongobbler that'd be wonderful. Thanks!
