### ISSUE TITLE
Allow interactive command sessions in `deis run`

### ISSUE THREAD

**Issue by jeroenvisser101** [deis/workflow-cli#98]
(from https://github.com/deis/deis/issues/117#issuecomment-188504543)

This seems to be a longstanding issue but something that would be super nice for Workflow.

Is this planned yet for v2? I couldn't find any issues referencing it.

**Comment by bacongobbler** [comment]
Hey @jeroenvisser101, this is not yet slated as something for v2, however now that we are using k8s this should be relatively easier to implement compared to v1.

**Comment by jeroenvisser101** [comment]
@bacongobbler would proxying this locally to `kubectl` be an option? That would make this very simple to implement, I think. (it would create a new runner pod, get the pod name, and then `exec -ti` in that pod, delete when done?)

**Comment by bacongobbler** [comment]
I don't think we can assume that the kubernetes api server is accessible to all users of workflow, which strikes out the idea of proxying to `kubectl`.

**Comment by bacongobbler** [comment]
The run implementation currently works like that (create a runner pod, get the pod name, wait for it to finish, retrieve the logs, delete when done), however the limitations are still the same as deis/deis#117. The limitation being that WSGI cannot handle long-running request/responses such as a websocket. We need to effectively create a new component to handle the proxying between the pod and the client outside of the controller... same for `deis logs -f` for deis/deis#465.

**Comment by rimusz** [comment]
any update on this?

**Comment by Cryptophobia** [comment]
This issue was moved to teamhephy/workflow-cli#28
